export const adventureMonsters = [
  'Bunch of Bees',
  'Giant Spider',
  'Mutant Water Bottle',
  'Dark Knight',
  'Hyper Giant Bowl',
  'Ogre',
  'Centaur',
  'Mutant Shoe',
  'Werewolf',
  'Chimera',
  'Golem',
  'Hyper Giant Aeronautical Engine',
  'Ent',
  'Mammoth',
  'Mutant \'ESC\' Key',
  'Cyclops',
  'Dinosaur',
  'Hyper Giant Door',
  'Attack Helicopter',
  'Hydra',
  'Mutant Book',
  'Hyper Giant Chest',
  'Kraken',
  'Leviathan',
  'Mutant Backpack',
  'War Tank',
  'Wyrm',
  'Hyper Giant Toilet',
  'Titan',
  'Typhon',
  'Mutant Dragon',
  'Ancient Dragon',
  'Even More Ancient Dragon',
  'Hyper Giant Dragon',
  'Ancientest Dragon',
  'Another Mutant Dragon Like In Area 11 But Stronger',
  'Yes, As You Expected, Another Hyper Giant Dragon But OP etc',
  'Just Purple Dragon',
  'I Have No More Ideas Dragon',
  'Mutantest Dragon',
  'Void Cone',
  'Void Cube',
  'Void Sphere',
  'Abyss Worm',
  'Shadow Creature',
  'Shadow Entity',
  'Corrupted Killer Robot',
  'Corrupted Mermaid',
  'Corrupted Dragon',
  'Black Hole',
  'Supernova',
  'Wormhole',
  'Time Annihilator',
  'Time Devourer',
  'Time Slicer'
];
